/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PokemonsIndexRouteImport } from './routes/pokemons/index'
import { Route as PokemonsIdIndexRouteImport } from './routes/pokemons/$id/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonsIndexRoute = PokemonsIndexRouteImport.update({
  id: '/pokemons/',
  path: '/pokemons/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonsIdIndexRoute = PokemonsIdIndexRouteImport.update({
  id: '/pokemons/$id/',
  path: '/pokemons/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pokemons/': typeof PokemonsIndexRoute
  '/pokemons/$id/': typeof PokemonsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pokemons': typeof PokemonsIndexRoute
  '/pokemons/$id': typeof PokemonsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pokemons/': typeof PokemonsIndexRoute
  '/pokemons/$id/': typeof PokemonsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/pokemons/' | '/pokemons/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/pokemons' | '/pokemons/$id'
  id: '__root__' | '/' | '/about' | '/pokemons/' | '/pokemons/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PokemonsIndexRoute: typeof PokemonsIndexRoute
  PokemonsIdIndexRoute: typeof PokemonsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemons/': {
      id: '/pokemons/'
      path: '/pokemons'
      fullPath: '/pokemons/'
      preLoaderRoute: typeof PokemonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemons/$id/': {
      id: '/pokemons/$id/'
      path: '/pokemons/$id'
      fullPath: '/pokemons/$id/'
      preLoaderRoute: typeof PokemonsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PokemonsIndexRoute: PokemonsIndexRoute,
  PokemonsIdIndexRoute: PokemonsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
